version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:

  flask-prometheus:
    container_name: flask-prometheus
    hostname: flask-prometheus
    build: images/.
    image: flask-prometheus-img
    volumes:
    # the value is taken from ".env" file
      - ${SRC_PATH}:/src
    command: sh start.sh
    ports:
      - 5050:5050

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
